version: '3'
services:
  dev-frontend:
    build:
      context: .
      dockerfile: deploy/docker/dev.frontend.Dockerfile
    ports:
    - "80:3000"
    links:
    - dev-web
    volumes:
    - ./src/mqueryfront/src:/app/src
    depends_on:
      - "dev-web"
  dev-web:
    build:
      context: .
      dockerfile: deploy/docker/dev.web.Dockerfile
    ports:
    - "5000:5000"
    links:
    - redis
    - postgres
    volumes:
    - "${SAMPLES_DIR}:/mnt/samples"
    - .:/usr/src/app
    depends_on:
      - "redis"
      - "postgres"
    environment:
      - "REDIS_HOST=redis"
      - "MQUERY_BACKEND=tcp://ursadb:9281"
      - "DATABASE_URL=postgresql://postgres:password@postgres:5432/mquery"
  dev-daemon:
    build:
      context: .
      dockerfile: deploy/docker/dev.daemon.Dockerfile
    links:
    - redis
    - ursadb
    - postgres
    volumes:
    - "${SAMPLES_DIR}:/mnt/samples"
    - .:/usr/src/app
    depends_on:
      - "redis"
      - "ursadb"
      - "postgres"
    environment:
      - "REDIS_HOST=redis"
      - "MQUERY_BACKEND=tcp://ursadb:9281"
      - "DATABASE_URL=postgresql://postgres:password@postgres:5432/mquery"
  ursadb:
    image: mqueryci/ursadb:v1.5.1
    ports:
    - "9281:9281"
    volumes:
    - "${SAMPLES_DIR}:/mnt/samples"
    - "${INDEX_DIR}:/var/lib/ursadb"
    user: "0:0"
  keycloak:
    image: quay.io/keycloak/keycloak:15.1.0
    ports:
    - "8080:8080"
    environment:
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=admin
    - DB_VENDOR=h2
  redis:
    image: redis
  postgres:
    image: postgres
    restart: always
    volumes:
      - ${POSTGRES_DIR}:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mquery
