version: '3'
services:
  dev-frontend:
    build:
      context: .
      dockerfile: deploy/docker/dev.frontend.Dockerfile
    ports:
    - "80:3000"
    links:
    - dev-web
    volumes:
    - ./src/mqueryfront/src:/app/src
    depends_on:
      - "dev-web"
  dev-web:
    build:
      context: .
      dockerfile: deploy/docker/dev.web.Dockerfile
    ports:
    - "5000:5000"
    links:
    - redis
    volumes:
    - "${SAMPLES_DIR}:/mnt/samples"
    - ./src:/usr/src/app/src
    depends_on:
      - "redis"
      - "ursadb"
  dev-daemon:
    build:
      context: .
      dockerfile: deploy/docker/dev.daemon.Dockerfile
    links:
    - redis
    - ursadb
    volumes:
    - "${SAMPLES_DIR}:/mnt/samples"
    - ./src:/usr/src/app/src
    depends_on:
      - "redis"
      - "ursadb"
  ursadb:
    build:
      context: ursadb/
      dockerfile: Dockerfile
    ports:
    - "9281:9281"
    volumes:
    - "${SAMPLES_DIR}:/mnt/samples"
    - "${INDEX_DIR}:/var/lib/ursadb"
  redis:
    image: redis
