"""add queuedfile
Revision ID: 702d19cfa063
Revises: 6b495d5a4855
Create Date: 2024-11-18 22:13:51.562315
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "702d19cfa063"
down_revision = "6b495d5a4855"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "queuedfile",
        sa.Column("index_types", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "ursadb_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("queuedfile")
    # ### end Alembic commands ###
