"""add queuedfile
Revision ID: 85ed22b90d72
Revises: 6b495d5a4855
Create Date: 2024-10-27 18:35:05.991934
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "85ed22b90d72"
down_revision = "6b495d5a4855"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "queuedfile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "ursadb_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("queuedfile")
    # ### end Alembic commands ###
