"""Modify_job status type to Enum
Revision ID: f552a27b4390
Revises: dbb81bd4d47f
Create Date: 2024-10-08 08:58:25.299726
"""
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = "f552a27b4390"
down_revision = "dbb81bd4d47f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "jobstatus",
        ["done", "new", "cancelled", "removed", "processing"],
        [
            TableReference(
                table_schema="public", table_name="job", column_name="status"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "jobstatus",
        ["done", "new", "cancelled", "removed", "processing"],
        [
            TableReference(
                table_schema="public", table_name="job", column_name="status"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
