"""Added context column into match table
Revision ID: f623e1057b00
Revises: 6b495d5a4855
Create Date: 2024-11-13 15:14:14.618258
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f623e1057b00"
down_revision = "702d19cfa063"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("match", sa.Column("context", sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match", "context")
    # ### end Alembic commands ###
