apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mquery-daemon
  name: mquery-daemon
  namespace: mquery-prod
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  selector:
    matchLabels:
      app: mquery-daemon
  template:
    metadata:
      labels:
        app: mquery-daemon
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: mquery-config
        - secretRef:
            name: mquery-secret
        image: dr.cert.pl/mquery/mquery_daemon:latest
        imagePullPolicy: Always
        name: mquery-daemon-container
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/samples
          name: mquery-nfs-volume-prod
        - mountPath: /mnt/kuku-analyses
          name: mquery-nfs-analyses-volume-prod
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dr-auth
      nodeSelector:
        kubernetes.io/hostname: mquery-supernode.cert.pl
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mquery-nfs-volume-prod
        persistentVolumeClaim:
          claimName: mquery-nfs-claim-prod
      - name: mquery-nfs-analyses-volume-prod
        persistentVolumeClaim:
          claimName: mquery-nfs-analyses-claim-prod
