apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mquery-web
  name: mquery-web
  namespace: mquery-prod
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: mquery-web
  template:
    metadata:
      labels:
        app: mquery-web
    spec:
      containers:
      - env:
        - name: MWDB_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: secret-mquery-mwdb-token
              key: token
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret-mquery-secret-key
              key: key
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        image: dr.cert.pl/mquery/mquery_web:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: mquery-web-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/samples
          name: mquery-nfs-volume-prod
        - mountPath: /mnt/kuku-analyses
          name: mquery-nfs-analyses-volume-prod
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dr-auth
      nodeSelector:
        kubernetes.io/hostname: mquery-supernode.cert.pl
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mquery-nfs-volume-prod
        persistentVolumeClaim:
          claimName: mquery-nfs-claim-prod
      - name: mquery-nfs-analyses-volume-prod
        persistentVolumeClaim:
          claimName: mquery-nfs-analyses-claim-prod
---
apiVersion: v1
kind: Service
metadata:
  name: mquery-web-service
  namespace: mquery-prod
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30111
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: mquery-web
  sessionAffinity: None
  type: NodePort
