#!/usr/bin/env python3

"""
Small utility for auto reloading job daemon
"""

import os
import sys
import subprocess
import time


def get_max_mtime():
    result, filename = 0, None
    for root, dirs, files in os.walk("."):
        for f in files:
            mtime = os.stat(os.path.join(root, f)).st_mtime
            if mtime > result:
                result, filename = mtime, f
    return result, filename


def run():
    return subprocess.Popen(
        sys.argv[1], shell=True, stdout=sys.stdout, stderr=sys.stderr
    )


def main():
    last_mtime, filename = get_max_mtime()
    process = run()

    while True:
        max_mtime, filename = get_max_mtime()
        if max_mtime > last_mtime:
            print(f"{filename} changed: restarting process.")
            last_mtime = max_mtime
            process.terminate()
            process.wait()
            process = run()
        time.sleep(5)


if __name__ == "__main__":
    main()
