name: Build and push docker images
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build_web:
    name: Build image
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build and push the image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./deploy/docker/web.Dockerfile
          repository: mqueryci/mquery-web
          tags: ${{ github.sha }}
          push: ${{ github.event_name == 'push' }}
  build_daemon:
    name: Build image
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build and push the image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./deploy/docker/daemon.Dockerfile
          repository: mqueryci/mquery-daemon
          tags: ${{ github.sha }}
          push: ${{ github.event_name == 'push' }}
